### ISSUE TITLE
backend error

### ISSUE THREAD

**Issue by sanskriti2102** [shubhamdhingra38/Quick-Grader-Backend#1]
![Screenshot (3)](https://user-images.githubusercontent.com/91959848/156349787-450cbfb3-4dff-4152-a4fe-4841adae022b.png)

please help us out !!!

will be waiting for your response.

**Comment by shubhamdhingra38** [comment]
@sanskriti2102 In `requirements.txt`, try removing the pin from the dependency (i.e. making `numpy==1.19.5` to just `numpy`)

**Comment by shubhamdhingra38** [comment]
Also consider using virtual environment if you're not

**Comment by sanskriti2102** [comment]
can you contact us ???
actually we have our presentation on 4th
so can you plz help us on that

whenever you are free we can have a meeting ..
waiting for your reply!

**Comment by shubhamdhingra38** [comment]
@sanskriti2102 Yeah I can get on a call if you wish, you could email me at dhingra.shubham38@gmail.com
